import React, { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./footer";

import styles from "../styles/footer.module.css";

import { FaArrowUp } from "react-icons/fa";

const Layout = (props) => {
  const [effect, setEffect] = useState(false);

  const toggleVisibility = () => {
    if (window.scrollY > 400) {
      setEffect(true);
    } else {
      setEffect(false);
    }
  };
  useEffect(() => {
    window.addEventListener("scroll", toggleVisibility);
    return () => {
      window.addEventListener("scroll", toggleVisibility);
    };
  }, []);

  return (
    <>
      <Head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
          integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
          integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/harry.jpeg" />
        <title>Haryy Poter Character</title>
        <link
          href="http://fonts.cdnfonts.com/css/harry-potter"
          rel="stylesheet"
        ></link>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/fontawesome.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <div>
        {props.children}
        <a
          href="#top"
          className={`${styles.topBtn} ${effect && styles.visible}`}
        >
          <FaArrowUp className={styles.topIcon} />
          <p>Yukarı</p>
        </a>
      </div>

      <Footer />
    </>
  );
};

export default Layout;
